stages:
  - name: madgraph
    dependencies: []
    scheduler:
      scheduler_type: singlestep-stage
      step: { $ref: "madgraph.yml" }
      parameters:
        outputlhe: "events.lhe"
        n_events: { step: init, output: n_events }
        param_card: { step: init, output: param_card }
        run_card: { step: init, output: run_card }
        proc_card: { step: init, output: proc_card }
        ufotar: { step: init, output: ufotar }
  - name: pythia
    dependencies: []
    scheduler:
      scheduler_type: singlestep-stage
      step: { $ref: "pythia.yml" }
      parameters:
        inputlhe: "events.lhe"
        outputhepmc: "{workdir}/output.hepmc"
        n_events: { step: init, output: n_events }
        pythia_card: { step: init, output: pythia_card }