stages:
- dependencies:
  - init
  name: generation_madgraph_pythia
  scheduler:
    parameters:
      n_events:
        output: n_events
        step: init
      proc_card:
        output: proc_card
        step: init
    scheduler_type: singlestep-stage
    workflow:
      stages:
      - dependencies:
        - init
        name: madgraph
        scheduler:
          parameters:
            n_events:
              output: n_events
              step: init
            outputlhe: events.lhe
            param_card:
              output: param_card
              step: init
            proc_card:
              output: proc_card
              step: init
            run_card:
              output: run_card
              step: init
            ufotar:
              output: ufotar
              step: init
          scheduler_type: singlestep-stage
          step:
            environment:
              environment_type: docker-encapsulated
              image: recast/madgraph
              imagetag: '2.6.7'
            process:
              process_type: interpolated-script-cmd
              script: '. ~/.profile

                python steer_madgraph.py {proc_card} {outputlhe} --ufotar {ufotar}
                --run_card {run_card} \

                --param_card {param_card} -n {n_events}

                '
            publisher:
              outputmap:
                lhefile: outputlhe
              publisher_type: frompar-pub
      - dependencies:
        - init
        name: pythia
        scheduler:
          parameters:
            inputlhe: events.lhe
            n_events:
              output: n_events
              step: init
            outputhepmc: '{workdir}/output.hepmc'
            pythia_card:
              output: pythia_card
              step: init
          scheduler_type: singlestep-stage
          step:
            environment:
              environment_type: docker-encapsulated
              image: recast/pythia
              imagetag: '8243'
            process:
              process_type: interpolated-script-cmd
              script: '. ~/.profile

                python steer_pythia.py {inputlhe} {hepmc} {n_events} {pythia_card}

                '
            publisher:
              outputmap:
                hepmc: hepmc
              publisher_type: frompar-pub
- dependencies:
  - init
  - generation_madgraph_pythia
  name: selection_rivet
  scheduler:
    parameters:
      analysis_id:
        output: analysis_id
        step: init
      hepmc:
        output: hepmc
        step: generation
    scheduler_type: singlestep-stage
    workflow:
      stages:
      - dependencies:
        - init
        name: rivet
        scheduler:
          parameters:
            analysis:
              output: analysis
              step: init
            hepmc:
              output: input
              step: init
            output_interface:
              output: output_interface
              step: init
            output_path: '{workdir}/output'
          scheduler_type: singlestep-stage
          step:
            environment:
              environment_type: docker-encapsulated
              image: recast/rivet
              imagetag: latest
            process:
              process_type: interpolated-script-cmd
              script: 'rivet -a {analysis} -H {yoda} {hepmc}

                '
            publisher:
              publish:
                yoda: '{yoda}'
              publisher_type: interpolated-pub
- dependencies:
  - init
  - selection_rivet
  name: statistics_pyhf
  scheduler:
    parameters:
      workspace:
        output: workspace
        step: init
      yoda:
        output: yoda
        step: selection
    scheduler_type: singlestep-stage
    workflow:
      stages:
      - dependencies:
        - init
        name: pyhf
        scheduler:
          parameters:
            outputcls: '{workdir}/cls.json'
            workspace:
              output: workspace
              step: init
            yoda:
              output: yoda
              step: init
          scheduler_type: singlestep-stage
          step:
            environment:
              environment_type: docker-encapsulated
              image: recast/pyhf
              imagetag: '0.1.2'
            process:
              process_type: interpolated-script-cmd
              script: 'python3 make_patch.py {workspace} {yoda} patch.json

                pyhf cls --patch patch.json {workspace} > {outputcls}

                '
            publisher:
              outputmap:
                clsjson: outputcls
              publisher_type: frompar-pub
